title: Apache Commons Configuration Code Execution Vulnerability
description: Palo Alto Vulnerability detection - Apache Commons Configuration Code
  Execution Vulnerability
tags:
- mitre.t1190
logsource:
  definition: THIRDPARTY_THIRDPARTY
  category: THIRD_PARTY_LOG
  product: PALO ALTO NETWORKS
detection:
  subname:
    eventSubName: vulnerability
  rule:
    ruleName: Apache Commons Configuration Code Execution Vulnerability*
  condition: subname and rule
level: info
taxonomy: tm-v1
